cmd: git add -A ; git commit -m "Auto Commit" -a ; git push origin master ; npm publish
targets:
  fully-deploy:
    cmd: git add -A ; git commit -m "Auto Commit" -a ; git push origin master; npm publish; cd ../casa-corrently-webinterface; npm install --save casa-corrently-ipfs-edge; cd ../casa-corrently-openems; npm install --save casa-corrently-ipfs-edge;
